### ISSUE TITLE
Borderlands doesn't trust Charles or Mitmproxy cert?

### ISSUE THREAD

**Issue by singh87** [apocalyptech/bl3hotfixmodding#1]
I am having issues with BL3 not trusting the proxy certificates on windows. I just wanted to know if this is a windows issue or if it's common with all platforms. I have added the certificate in the windows trusted root certificates store but BL3 doesn't want to trust it.

**Comment by apocalyptech** [comment]
Yeah, cert trust would be something that you'd have to figure out regardless of platform.  I'm afraid I really can't be of much help on Windows specifically, since I'm on Linux and the methods I use are very Linux-specific.  Maybe Charles has a forum/chat somewhere where you could ask for help on that end?  Someone who's familiar with those on Windows may be able to point you in the right direction.

Good luck!

**Comment by singh87** [comment]
> Yeah, cert trust would be something that you'd have to figure out regardless of platform. I'm afraid I really can't be of much help on Windows specifically, since I'm on Linux and the methods I use are very Linux-specific. Maybe Charles has a forum/chat somewhere where you could ask for help on that end? Someone who's familiar with those on Windows may be able to point you in the right direction.
> 
> Good luck!

Thanks for pointing me to the right direction. I think I figured it out.

**Comment by apocalyptech** [comment]
Cool, glad to hear it.  Enjoy!
