### ISSUE TITLE
About account data spoof

### ISSUE THREAD

**Issue by yurii-sio2** [apocalyptech/bl3hotfixmodding#4]
Hi. Thank you for your project.

I have a question about account data spoof. What steps have user to complete to run the proxy in mode that will do both things: process account requests and hotfixes request?

What command line arguments should user provide? What configuration should be done to pretend as authorized user?

I saw some ids and tokens in file account_other.json. Where can I get them?
May be you can add more info about this to the readme?

**Comment by apocalyptech** [comment]
Heya!  I've actually not really looked closely into anything but intercepting hotfixes.  During a Shift outage almost a year ago, I started to take a look at what might be required to pretend to be GBX's entire infrastructure, but I didn't really get anywhere with it, and didn't keep looking once Shift was back up.

If you did want to capture *all* the network traffic from the game, with mitmproxy, you'd want to be running `mitmproxy` in "transparent" mode (`-m transparent`), and make sure that the routing on the box running BL3 sends the necessary traffic over to the proxy box.  The main wrinkle there is that neither EGS nor Steam takes kindly to being MITM'd -- they're both doing some cert pinning, it seems like -- so you'd need to make sure that *that* traffic doesn't go through your proxy.  I'd vastly overengineered that, myself, and I've got BL3 running under its own system user, which I can use to mark packets using techniques like from here: https://tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.netfilter.html

Then, so that I'm *only* sending the GBX traffic through the proxy, I rigged up a ridiculous little script to do DNS lookups every 5 seconds and keep an iptables chain updated with the marking instructions, for the various GBX hostnames I was aware of: https://gist.github.com/56c71ebfc91867002a2072675b916c69

Quite a bit of work, in the end, and as I say, I didn't even get to the point of making it work.  :)  Intercepting *just* hotfixes is a much more straightforward process.  :)

**Comment by apocalyptech** [comment]
Gonna go ahead and close this out -- something I'd like to do at some point still, but I seem unlikely to spend much time working on it anytime soon.

(Also, I noticed on c0dycode's B3HM Issues that you mention this is a pirated/torrented version anyway, and nothing I do here would help you in that case anyway (and I also won't support any pirated copies of the thing), so this'd be a dead end for you regardless.)
